# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  text2shape: # name of the dataset builder
    dataset_card: dataset_card/text2shape.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /root/data/text2shape/annotations/text2shape_train.json
          storage: text2shape/annotations/text2shape_train.json
        val:
          url: /root/data/text2shape/annotations/text2shape_val.json
          storage: text2shape/annotations/text2shape_val.json
        test:
          # url: /root/data/text2shape/annotations/text2shape_test.json
          # storage: text2shape/annotations/text2shape_test.json
          url: /root/data/text2shape/annotations/text2shape_airplane.json
          storage: text2shape/annotations/text2shape_airplane.json
      images:
        storage: /root/hdd3/text2shape/rendering/ # HDD
        # storage: text2shape/images/ # cache